### ISSUE TITLE
pipes.sh: 第 100 行:read: 设定终端属性时出错: Interrupted system call

### ISSUE THREAD

**Issue by wenerme** [pipeseroni/pipes.sh#11]
pipes.sh: 第 100 行:read: 设定终端属性时出错: Interrupted system call

on Mac OS

```
# bash -version
GNU bash，版本 4.3.33(1)-release (x86_64-apple-darwin14.1.0)
Copyright (C) 2013 Free Software Foundation, Inc.
许可证 GPLv3+: GNU GPL 许可证第三版或者更新版本 <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by livibetter** [comment]
I am still running Bash 4.2, don't know if this only happens in 4.3. Did this happen before any pipes showed or after some time running?

We might have to go back to pure `sleep`, could you try to put the following line before line 100 and see if it runs without any issues:

```bash
SLEEP='sleep 0.013'
```

Probably wouldn't matter, but could you check `read -t0.013 -n 1; echo $?` to see if that gives 142?

**Comment by wenerme** [comment]
```
SLEEP='sleep 0.013'
```
fix the error message,but can not press any key to exit.

```
read -t0.013 -n 1; echo $?
```
the output is `142`

**Comment by wenerme** [comment]
BTW, what the font of you terminal use ?
pipes in my terminal is not as good as the screenshot in README

**Comment by livibetter** [comment]
Only `Ctrl+C` can exit when use `sleep` for sleeping. With Bash 4, we use `read` to handle sleeping, but for some reason, your system threw out that "Interrupted system call" error message. I still don't know if this is a Bash 4.3 issue or not since I don't have 4.3.

I have only seen that message when a program is updating within tmux pane and the the pane is also being resized at the same time. You wouldn't have been in this exact situation, would you?

I think I will put this issue on hold since you are the only one getting this issue and I have no way to reproduce the issue, it'd be better to let this one sit here and see if anyone else can also confirm the issue or better way to handle delay and user inputs.

----

I use Envy Code R in urxvt, but I don't think all those are Envy Code R's glyphs, at least not those Unicode characters, I believe.

**Comment by wenerme** [comment]
I use iterm2, so the pipese is run in tmux, but I don't resize it.

2015-03-20 15:38 GMT+08:00 Yu-Jie Lin <notifications@github.com>:

> Only Ctrl+C can exit when use sleep for sleeping. With Bash 4, we use read
> to handle sleeping, but for some reason, your system threw out that
> "Interrupted system call" error message. I still don't know if this is a
> Bash 4.3 issue or not since I don't have 4.3.
>
> I have only seen that message when a program is updating within tmux pane
> and the the pane is also being resized at the same time. You wouldn't have
> been in this exact situation, would you?
>
> I think I will put this issue on hold since you are the only one getting
> this issue and I have no way to reproduce the issue, it'd be better to let
> this one sit here and see if anyone else can also confirm the issue or
> better way to handle delay and user inputs.
> ------------------------------
>
> I use Envy Code R in urxvt, but I don't think all those are Envy Code R's
> glyphs, at least not those Unicode characters, I believe.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/livibetter/pipes.sh/issues/11#issuecomment-83943721>.
>



-- 
Wener~~~~~~~~

**Comment by livibetter** [comment]
@wenerme I just pushed b267c7a, could you check it out? Although, I don't think it would fix this issue.

**Comment by wenerme** [comment]
I tried, it's not fix~ same problem.

2015-04-08 12:56 GMT+08:00 Yu-Jie Lin <notifications@github.com>:

> @wenerme <https://github.com/wenerme> I just pushed b267c7a
> <https://github.com/livibetter/pipes.sh/commit/b267c7a37ee9c128b120bb11395aeb86d438ece7>,
> could you check it out? Although, I don't think it would fix this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/livibetter/pipes.sh/issues/11#issuecomment-90801732>.
>



-- 
Wener~~~~~~~~

**Comment by wkentaro** [comment]
maybe I also have the same problem
<img width="1280" alt="screen shot 2015-08-20 at 3 11 21 pm" src="https://cloud.githubusercontent.com/assets/4310419/9376877/c1de8b62-474d-11e5-8ddb-393dca1a6603.png">

How can I fix this? redirect the stderr to /dev/null like https://github.com/pipeseroni/pipes.sh/pull/17 ?
