### ISSUE TITLE
Who is the original author of pipes.sh?

### ISSUE THREAD

**Issue by livibetter** [pipeseroni/pipes.sh#13]
As I wrote in `README`:

> The author of the original script is unknown to me. The first entry I can
find was posted at 2010-03-21 09:50:09 on [Arch Linux Forums][post] (doesn't mean the
poster is the author at all).

[post]: https://bbs.archlinux.org/viewtopic.php?pid=728932#p728932

I really want to properly license this project, so I think we need a place to gather information, somebody must know something. If you know anything about `pipes.sh`, please leave a comment.

**Comment by livibetter** [comment]
If one day we do know the author and obtain a written statement about the license, we also need to make sure the current and future contributors would agree.

Current contributors who have agreed:

- [x] @livibetter
- [ ] @dsamarin 
- [ ] @Foggalong 

Here is my proposal:

> The first option is the *MIT License*, however, if the original author chooses other open source license, as long as it is [OSI-approved][OSI] license, you, the contributors, will automatically agree without needing any confirmation from you.

[OSI]: http://opensource.org/licenses

Once the current contributors have all agreed, I will edit `README` and add `CONTRIBUTING` to make sure the future contributors are aware that once they create a PR for this repository, they will give they consent about the license agreement.

----

Now, @dsamarin and @Foggalong do you agree?

**Comment by Foggalong** [comment]
Yup, that is fine by me!

**Comment by dsamarin** [comment]
This is so old that my own code looks foreign to me. Still, I can only accept a *permissive* OSI-approved license.

**Comment by livibetter** [comment]
@dsamarin guess you are really making my life harder.

Do you have a clear definition of the "permissive" or the best, a list by well-recognized organization?

By the way, I am quite shocked hearing you want to only accept that, usually, when comes to this I often see people going towards licenses like GPL.

Luckily, the first choice is MIT, that would be fine, but the second part would have to add "permissive," however, I need a clear definition of that and since I am not a lawyer, even you do give me the definition, I doubt that I could decide whether one is permissive or not, so a list really is the best one, that's why I chose "OSI-approved."

If you can't, I think the last option is you give me a list of yours. We need a list of choices, just in case the original author doesn't like MIT License.

**Comment by livibetter** [comment]
@dsamarin haven't heard from you, but it's okay because I realized I used "public domain" in `README`, so I need to make a revision.

The following is what I am planning to write about it:

----

Upon on the creation of pull requests, you agree to allow @livibetter or anyone else to contact the original author on your behalf in order to obtain a written permission using the following order:

1. Public domain via [Unlicense][]

2. Permissive [OSI-approved][OSI] open source license

    The [definition of "permissive"][def] is:

    > A "permissive" license is simply a non-copyleft open source license — one that guarantees the freedoms to use, modify, and redistribute, but that permits proprietary derivative works.

    Since there is no organizations actually listing, they would be those listed in [Wikipedia][list] with "Permissive" under columns "Distribution" and "Modification".

[Unlicense]: http://unlicense.org/
[OSI]: http://opensource.org/licenses
[def]: http://opensource.org/faq#permissive
[list]: http://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

Please be advised, since we are modifying without permission, the original author might not agree on anything. That's if he chooses to license non-permissive, we can only go for it; or even demand a complete removal.

----

Frankly, I don't really like it so complicated, but there is no list as far as I can tell.

Anyway, I need your response, so I can continue.

**Comment by livibetter** [comment]
It's been two weeks, @dsamarin, do you copy my last comment?

I'll wait for another two, if I still don't get any responses from you, I will do it with my original plan, Public Domain/OSI-approved for negotiating with the original author since we don't have legal ground to demand, anyway.

I'll be happy to do what you wanted as long as you provide me a list or a strict definition of "permissive," but I can't do either if I got no answers from you.

----

This issue would be retitled/repurposed for this legal matter, since it's been amazingly off-tracking. The asking of original author will be re-created to make a clean issue.

**Comment by dsamarin** [comment]
A "permissive" license is simply a non-copyleft open source license — one that guarantees the freedoms to use, modify, and redistribute, but that permits proprietary derivative works.

I'm not a fan of copyleft, especially for something like pipes.sh. Apologies for the late reply.

**Comment by livibetter** [comment]
@ all and @pipeseroni/owners:  I've decided to delete this repository while composing a reply. We were doing without permissions and I've even been asking among contributors about licenses, which proved not quite simple as I hoped, now that really sounds crazy for me.

I'll will be making a removal notice branch and switch to it, so everyone would know this repository is subjected to deletion after June. Anyone will have time to preserve our possibly copyright violating content or to continue most likely illegally.

This, of course, can be reversed if somehow the original author shows up and kindly licenses it for us with anything we want, but don't count on it.

@pipeseroni/owners if I forget when clock hit July, please hit the delete button for me.

----

The following is my original reply to @dsamarin, just for the record:

@dsamarin what does "permits proprietary derivative works" actually mean? I feel this is too much of ambiguity. Does that mean one can relicense?

I already quoted the very same definition, and still need a way to find out if one is permissive or not, without needing to read license text, even I have time, I doubt I could completely sure. I was thinking about to check with [this page][], but that doesn't seem to cover every permission point in that definition.

Again, do you know if there is a **list**?

Frankly, I fear the original author would have good chance to choose GPL, I would really hope you can ease up on your likings. And after all, he or she might not even license under any OSI-approved, but just give me one line of words.

I begin to think I should have just axed this repository to save me from all these troubles. Can't even get an easy way out among us.

[this page]: http://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses#General_comparison

**Comment by livibetter** [comment]
Additional thought, if anyone wants to take over, in case of preserving issues, forks/stars counts, let me know before July. I will be gladly transfer to your account.

**Comment by Foggalong** [comment]
@livibetter Isn't deleting the whole thing a bit extreme? We could always just continue the work "unlicensed" as was originally found. I would think that the research done and notice appealing for the original author to come forward is enough to demonstrate that we've made an effort to find the creator. As far as I know that's sufficient evidence in cases of dubious copyright ownership.

**Comment by livibetter** [comment]
@Foggalong It's if you don't respect the law and the original author. I shouldn't have even put my modification on Gist in first place, no, I shouldn't have even modified it in the first place.

I always told myself to be sure I know who wrote a piece of code and I know I have been permitted to do something about before I start making changes. But once in a while, in this <del>case</del> pipe, I got water leakage, overflew my head. I ignored when I posted on Gist, ignored again when moved on to GitHub.

Even I did sign my name when I posted to Gist, in case the original author needs a name to sue. Even I did put up a sign about my copyright concern, even I did try to find the author, googling with date ranges, even wayback machine.

1. Have I showed my efforts to find the creator?
2. Have I contributeed to make pipes.sh better?
3. Do I take responsibility of violating the rights?

My honest answer to three is yes, but that doesn't right the wrong. It's not just the law, which might give me some leeway, it doesn't matter if you and anyone else knows *sufficient evidence*. What's wrong is wrong, in law and/or personal principle.

I've to put a stop for myself, the deletion doesn't mean I am trying to avoid legal issue, my name is in the copies of Gist and Git commits, but I don't want anymore (by others) to be adding to it, because of me and this repository somewhat encouraging.

If you (@Foggalong)  want to continue, you can transfer it under your account. As long as I am active @pipeseroni, illegal -- even just possibly -- content would not be staying, it has to go away after June.

**Comment by livibetter** [comment]
@pipeseroni/owners after my last comment, the word, "active," got me thinking of a better option.

How abort me removing myself from @pipeseroni? I think that's why I happened to start it and invited you guys. somehow, this outcome would be coming, only I didn't know at the time.

So, once I remove myself, this repository can be kept untouch, no dead links.

By removing, it means I will also unwatch every reposiotry, unsubscribe from issues, but you can still @ me, if I am needed. I will wait for a bit, most likely after sleep, which I will be doing soon, before I end my piping days, if nothing comes up to change my mind.

@Foggalong and @OneLastTry, I am sure you two can handle, right?

**Comment by Foggalong** [comment]
Out of curiosity I [looked up the diff between](https://www.diffchecker.com/ysohw5l4) the original posted script and the script as it stands now. Interesting to see the little bits of the original that are still left.

**Comment by Foggalong** [comment]
@pipeseroni/owners 

But anyway, back to the matter at hand. I've spent the last hour or so trawling the internet trying to find any earlier mention of the script. I could find literally no mention of it prior to that. The other response by the user in that thread leads me to think that they ("GraveyardPC") is the original creator.

Started looking around from there for other accounts of the same name. Got to [this Facebook](https://www.facebook.com/graveyardpc.bon), [this LiveLeak channel](http://www.liveleak.com/c/graveyardpc) [this GeForce Forum](https://forums.geforce.com/member/1599325/), [this Dropbox account](https://dropboxusercontent.com/u/519931), and [this dA](http://graveyardpc.deviantart.com/).

Not sure about the others, but looking through their other posts on ALF it seems they had a penchant for design which makes me thing the dA will be legit. The account also has several screenshots of tiling Linux with window managers which is a good sign. The account has been active as recently as last September too which is promising. If this is the same person the screenshots show us that their name is "Matt". 

That dA account (specifically [this post](http://graveyardpc.deviantart.com/art/TF2-Engineer-Update-124093009)) also suggests they go by the name "Zom13ie", possibly on gaming services. That brought up several accounts including [this Twitch](http://www.twitch.tv/zom13ie), [this Twitter](https://twitter.com/zom13ie) & [this Twitter](https://twitter.com/e63ed056f9e0461), [this Instagram](https://instagram.com/zom13ie/), this [Steam profile](http://steamcommunity.com/profiles/76561197989690083). Most of those look like dead ends to me to be honest, but still worth a look.

I've sent messages to most of the people that could know if I'm looking in the right direction so I'll update as I hear back from people.

**Comment by Foggalong** [comment]
Someone on Steam got back to me letting me know that the profile linked above is a dead end. That person is called Christopher so probably not our guy. We can also rule out the Twitter accounts because they have the wrong name too.

I did find [this](https://github.com/0xAether/pipes) on GitHub and while there are some differences there are [some striking similarities](https://www.diffchecker.com/dktnnvrk) too. That user hasn't been active on GitHub for years though and nor on their linked Wikipedia account. Interestingly though it suggests that the script was originally written for OSX and ported to Linux which differs from being originally posted on an Arch forum.

**Comment by livibetter** [comment]
@Foggalong looked like you are trying very hard to find the identity of the author, remaining me I even searched on GitHub with code piece, googled with comments in quote. Nothing. I'd hope either someone made some notes in header comments about the author or the real original first post of the code which had completely header comment that has information written by the original author.

I found it's hard to believe a *group* would not sign their works with some kind of fancy ASCII art work. I did believe that's a possibility that someone took the code and removed the comments that could help find the author, that happened to me once or twice, someone just copied the entire code and deleted first few lines of comment or edited out the important information.

It's been more than two years since I posted my modified version on Gist, and one+ year on GitHub, never got a tip about the author. Frankly, I've given up the hope. It's been dragging too long, and this is it.

**Comment by Foggalong** [comment]
Just found confirmation that the user on the Arch forums is the one on the dA. Found [this forum post](https://bbs.archlinux.org/viewtopic.php?id=60188) from 2008 which says that his home directory is `/home/matt/`. Progress \O/

**Comment by dsamarin** [comment]
That's great detective work! I'm impressed.

I have a hunch that he will not mind his work to be licensed under some or any OSI-approved license. This Matt person has work under the GPL. Also, I believe he was the one who posted the original code to pastebin not caring what happened to it. `pipes.sh` is unique and is a great piece of code; I would hate for it to get lost.

**Comment by Foggalong** [comment]
Reading through their forum post I've found another user (with public email address) to whom Matt has some connection. I've email this user to see if they can give us anymore details :)

**Comment by Foggalong** [comment]
@livibetter @dsamarin I've found him!

1. [This original post...](https://bbs.archlinux.org/viewtopic.php?pid=728932#p728932)
2. [...lead me to this dA](http://graveyardpc.deviantart.com/)
3. [Cross referenced the name with this post ](https://bbs.archlinux.org/viewtopic.php?id=85739)
4. [Found this dA comment thread...](http://comments.deviantart.com/1/278081541/3090036586)
5. [...which linked to this gist...](https://gist.github.com/msimpson/5804612)
6. [...connected to this GitHub account...](https://github.com/msimpson)
7. [...that has a public email address!](http://i.imgur.com/7drHiqr.gif)

Best part about it, he's been active on GitHub within the last month! I've emailed him to ask about then licensing of the original script and if they're cool with it whether they'd like to join the organisation as honorary leader. Finally, the end is in sight!

**Comment by msimpson** [comment]
Woah ... You people have done way too much to find me. The work is public domain and you guys can certainly have it as the basis of your project.

**Comment by OneLastTry** [comment]
@Foggalong, that is some impressive detective work!

**Comment by dsamarin** [comment]
Haha this resolved fantastically. I appreciate the effort involved into finding the original author and it was somewhat entertaining. Screensaver bash scripts are in high demand, too.

I am in favor of the MIT license for this project.

**Comment by Foggalong** [comment]
@msimpson Are we okay to move the project over to the MIT license or do you wish for it to remain in the public domain?

**Comment by msimpson** [comment]
@Foggalong Go for it.
