### ISSUE TITLE
invalid timeout specification

### ISSUE THREAD

**Issue by mekhami** [pipeseroni/pipes.sh#15]
I'm trying to run this on ZSH, OS X. I get this error, pointing to line 102 (can't really copy paste it, it flies by during runtime) and the script doesn't work.

**Comment by livibetter** [comment]
pipes.sh now only support Bash 4+.

**Comment by livibetter** [comment]
If you have Bash 3, you can try check out b3e2253ff3c6c01fb718af262db9c2a6b72736e0, see [CHANGES][]. I don't believe pipes.sh would work with ZSH.

[CHANGES]: https://github.com/pipeseroni/pipes.sh/blob/69a209e07021cb9c9032570401ea9ca23ad0387e/CHANGES.rst#version-100-2015-04-09t024133z
