### ISSUE TITLE
Add LICENSE file on tarball

### ISSUE THREAD

**Issue by diogoleal** [pipeseroni/pipes.sh#24]
My sugestion is you add a license file in tarball. Because I not found any reference for MIT license.

**Comment by Foggalong** [comment]
@diogoleal This is just because the latest released version was before we found out what the original script was MIT licensed. Once the next release is reached this will be rectified :)

**Comment by Foggalong** [comment]
The license is now included in the tarball of the latest release, [1.2.0](https://github.com/pipeseroni/pipes.sh/releases/tag/v1.2.0)
