### ISSUE TITLE
Division by 0 in Cygwin

### ISSUE THREAD

**Issue by ijustlovemath** [pipeseroni/pipes.sh#26]
Sample output:

    /usr/local/bin/pipes.sh: line 16: tput: command not found
    /usr/local/bin/pipes.sh: line 16: tput: command not found
    /usr/local/bin/pipes.sh: line 107: tput: command not found
    /usr/local/bin/pipes.sh: line 108: tput: command not found
    /usr/local/bin/pipes.sh: line 109: tput: command not found
    /usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[33m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[31m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[30m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[30m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[37m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[36m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[37m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[31m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[31m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[33m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")
    /usr/local/bin/pipes.sh: line 127: tput: command not found
    [1m[35m?/usr/local/bin/pipes.sh: line 118: x[i]=(x[i]+w)%w: division by 0 (error token is "w")
    /usr/local/bin/pipes.sh: line 119: y[i]=(y[i]+h)%h: division by 0 (error token is "h")

**Comment by muthdra** [comment]
Install ncurses-utils

**Comment by ijustlovemath** [comment]
Solved, thanks
