### ISSUE TITLE
Put this on AUR

### ISSUE THREAD

**Issue by jakevossen5** [pipeseroni/pipes.sh#29]
I would love to see this put on the AUR. It would make updating and everything much easier. That would be awesome!

**Comment by Foggalong** [comment]
There is a copy of the script currently available in the AUR, and I've appealed to the owner to see if they'd be interested in joining the project here.

**Comment by jakevossen5** [comment]
Sweet, good to know!

Thank you.

**Comment by livibetter** [comment]
A quick search for [pipes on AUR][aurpipes] showed only one [bash-pipes][], @Acidhub's [fork][acidhub].

[aurpipes]: https://aur.archlinux.org/packages/?K=pipes
[bash-pipes]: https://aur.archlinux.org/packages/bash-pipes/
[acidhub]: https://github.com/Acidhub/pipes.sh

A vanilla would also be nice right?  (just please don't include PKGBUILD, once you do, other distributions' packaging script would come in, might even some listing/directory manifest files, perhaps create a `pkg-pipes.sh` repo to host all those kind of files, I'm not very inventive about naming)

Anyway, should this be closed?

**Comment by livibetter** [comment]
I am closing this, because it'd have to have a discussions with Packagers team, which doesn't exist at this moment.  Once we do get people on board of that team, the discussions will be in their repo or team discussion board.

@jakevossen5 Would you like to join and help packaging?  See #37.
