### ISSUE TITLE
Merge in changes from Acidhub

### ISSUE THREAD

**Issue by Foggalong** [pipeseroni/pipes.sh#31]
A user @Acidhub has made some enhancements to pipes.sh that I'd like to merge in here, the most attractive of which to me is the repository streamlining. So they get credit for their work I'm going to create a branch of pipeseroni/pipes.sh which I'll merged their changes into, from there modifying it until a pull request can be made.

**Comment by livibetter** [comment]
From its [latest commit's blame[c], I don't see anything new but that resize feature, which already in dcba3bc3aaf7b73e7c9901f5e28c5444e0c03706

[c]: https://github.com/Acidhub/pipes.sh/blame/f40dad0caef5d83a9487e5fccf24c3f19709edf6/pipes.sh

Unless I missed something, this can be closed.
