### ISSUE TITLE
Cleanup doesn't work as expected

### ISSUE THREAD

**Issue by agustinmista** [pipeseroni/pipes.sh#34]
Sometimes,  when I quit pipes.sh by pressing a key, the terminal keeps showing some pipes until they are overriden by new standard outputs.

Adding `clean` just before `exit 0` on cleanup seems to fix this at least for me.

[Here](http://pastebin.com/dS6yHbyB) is a patch if I wasn't clear enough

I hope you find this useful!

**Comment by livibetter** [comment]
What's your OS and terminal emulator?

That clear fix isn't ideal as it would overwrite the restore screen.  When pipes.sh runs it save the current screen and restore when exits, could you take a screenshot of what exactly you see.  I suspect the save/restore doesn't work in your terminal.

**Comment by agustinmista** [comment]
Hey, it was an issue using bash and Terminator under Ubuntu 16.04 iirc. With a newer version of both packages it seems to be working properly. I'm closing this issue.
