### ISSUE TITLE
"error setting terminal attributes: Interrupted system call" when focusing back on the terminal

### ISSUE THREAD

**Issue by SteppingHat** [pipeseroni/pipes.sh#35]
When focus is removed from the terminal onto any other application, on resuming focus onto the terminal, the following message appears where the cursor is currently at.

`usr/local/bin/pipes.sh: line 101: read: error setting terminal attributes: Interrupted system call`

This happens on macOS in both iTerm2 and Terminal. The length of time where the terminal is out of focus seems irrelevant. This also occurs when simply switching between tabs.

![image](https://cloud.githubusercontent.com/assets/1788634/24132066/af7a0994-0e46-11e7-8962-83b9bbd06a5b.png)

**Comment by OliverHofkens** [comment]
This is supposedly fixed in v1.2 ( See #27 and #17 ), but the homebrew formula installs v1.1 ([pipes-sh.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pipes-sh.rb))
