### ISSUE TITLE
Changes the colour of the terminal text

### ISSUE THREAD

**Issue by Foggalong** [pipeseroni/pipes.sh#5]
Ubuntu terminator. Upon exiting pipes it changes the colour of the terminal text to the colour of the last pipe drawn until that terminal window is closed. It only affects the terminal pipes was ran in. This could almost be marketed as a feature instead of a bug but some of the pipes are white and black meaning that people with terminals of those colours won't be able to see their commands.

![screenshot - 090314 - 11 10 17](https://f.cloud.github.com/assets/5920259/2367798/56987fa6-a77c-11e3-81c4-28fde9abd9e8.png)
![screenshot - 090314 - 11 09 41](https://f.cloud.github.com/assets/5920259/2367799/56993572-a77c-11e3-953e-891c32c3a708.png)
![screenshot - 090314 - 11 09 27](https://f.cloud.github.com/assets/5920259/2367800/569ae2d2-a77c-11e3-91f6-51988f9963c0.png)
![screenshot - 090314 - 11 09 55](https://f.cloud.github.com/assets/5920259/2367797/56973a4c-a77c-11e3-815e-92c00e1f5887.png)
![screenshot - 090314 - 11 09 09](https://f.cloud.github.com/assets/5920259/2367801/569c17f6-a77c-11e3-9aeb-0e30d94194e9.png)

**Comment by arionrefat** [comment]
How can I set it to particular color of my choice
