### ISSUE TITLE
Terminal locker

### ISSUE THREAD

**Issue by jarun** [pipeseroni/pipes.sh#68]
Hey guys,

Author of file manager `nnn` here. Call it temptation but I was kind of compelled to [add](https://github.com/jarun/nnn/commit/4a98d8db50e2585fc1e02925fe257ac9654e2bdc) pipes.sh as the fallback locker. :cheese: 

Excellent work and I love the perfection with which it renders even in 8-bit. I work in a drab screen (with MOC playing in bg) most of the time but `pipes.sh` kind of brings the charm back every time I see it. ;)

Would it be possible to support terminal locking facility (something like `bashlock`)?

**Comment by jarun** [comment]
Closing the issue.

**Comment by StefansM** [comment]
Hi @jarun,

Glad to hear you're enjoying it. How do you envision pipes.sh working with a terminal locker? I'm not sure what would be required.

**Comment by jarun** [comment]
> How do you envision pipes.sh working with a terminal locker?

Yes, I now see it might be an issue. The mechanism is not very standardized across OSes so the same implementation may not work everywhere. Thanks for your response!
