### ISSUE TITLE
pipes.sh -t (0-3) not rendering correcting in Konsole

### ISSUE THREAD

**Issue by jadedgal** [pipeseroni/pipes.sh#79]
i run
`pipes.sh -t {0-3}
` and it gives me the following image (after a while)
[Tue-Sep-2402-18-57](https://github.com/user-attachments/assets/b438c692-0dfe-439b-8b9e-7272b55ef152)
however I can run something like
`echo -e '\u2502 \u2500 \u250C \u2510 \u2514 \u2518'
`

and it will output ![the ascii characters.](https://github.com/user-attachments/assets/a1514896-1756-4f55-8577-deecf0e4965b)
edit, It is fixed when I use the US locale and not the GB one

**Comment by whiteawake** [comment]
For anyone else with this problem: you can preface the command with `LANG=en_US.UTF-8` if you, like me, don’t want to change your entire locale to American just to run this program.
